# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mnist_recognite_QtDesigner.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtWidgets, QtCore, QtGui
from PyQt5.QtWidgets import *
from Function import *
import sys

class Ui_MainWindow(QWidget):
    def __init__(self):
        QMainWindow.__init__(self)
        self.img_path = ""

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Button_select_img = QtWidgets.QPushButton(self.centralwidget)
        self.Button_select_img.setGeometry(QtCore.QRect(340, 140, 151, 23))
        self.Button_select_img.setObjectName("Button_select_img")
        self.label_pre_img = QtWidgets.QLabel(self.centralwidget)
        self.label_pre_img.setGeometry(QtCore.QRect(70, 180, 200, 200))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_pre_img.setFont(font)
        self.label_pre_img.setObjectName("label_pre_img")
        self.Button_click = QtWidgets.QPushButton(self.centralwidget)
        self.Button_click.setGeometry(QtCore.QRect(340, 410, 141, 23))
        self.Button_click.setObjectName("Button_click")
        self.label_pre_img_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_pre_img_2.setGeometry(QtCore.QRect(600, 180, 200, 200))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_pre_img_2.setFont(font)
        self.label_pre_img_2.setObjectName("label_pre_img_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.Button_select_img.clicked.connect(lambda: self.openimage())
        self.Button_click.clicked.connect(lambda: self.recognite())

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Button_select_img.setText(_translate("MainWindow", "选择数字照片"))
        self.label_pre_img.setText(_translate("MainWindow", "待识别图片"))
        self.Button_click.setText(_translate("MainWindow", "点击进行识别"))
        self.label_pre_img_2.setText(_translate("MainWindow", "识别结果"))

    def openimage(self):
        path_photo = "D:\\Desktop\\Program\\Python\\Machine_learn\\mnist_ann"
        self.img_path = QFileDialog.getOpenFileName(self, "打开图片", path_photo, "*.jpg;")[0]
        print("待测图片地址：\n",self.img_path)
        img = QtGui.QPixmap(self.img_path).scaled(self.label_pre_img.width(), self.label_pre_img.height())
        self.label_pre_img.setPixmap(img)

    # 输出识别结果图片
    def recognite(self):
        predict_img(self.img_path)
        path_result = "D:\\Desktop\\Program\\Python\\Machine_learn\\mnist_ann\\UI\\result.jpg"
        img = QtGui.QPixmap(path_result).scaled(self.label_pre_img_2.width(), self.label_pre_img_2.height())
        self.label_pre_img_2.setPixmap(img)

if __name__ == '__main__':
    app = QApplication(sys.argv)
    MainWindow = QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())